---
title: "Oct 9"
author: "Aidan Fauth"
format: html
editor: visual
---

## Set up

```{r}
rm(list=ls())
library(tidyverse)
library(here)
```

Read in tomato data set:

```{r}
tomatoes = read.csv(here("Data", "tomato_data.csv")) #use View() makes it easier to see
```

Write a line of code that returns the 3rd, 7th, and 9th rows of data:

```{r}
slice(tomatoes, c(3,7,9))
```

```{r}
filter(tomatoes, Treatment == "fertilizer" & Avg_tomato_weight_g >=145)
```

Save your changes (to a new file in an output folder)

Make the output folder

```{r}
dir.create(here("Outputs"))
```

Now save the file

```{r}
write.csv(tomatoes,here("Outputs", "tomatoes_fixed.csv"),row.names = FALSE)
```

```{r}
toms2 = read.csv(here("Outputs", "tomatoes_fixed.csv"))
```

```{r}
lead = read.csv(here("Data", "NoColead.csv"))
summary(lead)
```

What if we want to know the average number of tests given in the data set?

```{r}
lead %>% summarise(
  mean_num_tests = mean(num_tests)
) %>% View()
```

What is the mean number of test per year?

```{r}
lead_summary = lead %>% 
  group_by(Year) |>
  summarise(mean_tests_per_year = mean(num_tests)
  )
```
